image: docker:stable
services:
  - docker:19.03.5-dind

variables:
  NAME: robolucha/game:latest
  CONTAINER_IMAGE: robolucha/game:${CI_COMMIT_SHORT_SHA}
  DOCKER_USER: gitlab
  LATEST: ${DOCKER_SERVER}/${NAME}

build:
  stage: build
  script:
    - docker --version
    - docker login --help
    - echo  "${DOCKER_USER}" "${DOCKER_PASSWORD}" ${DOCKER_SERVER}
    - docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}" ${DOCKER_SERVER}
    - docker build -t ${CONTAINER_IMAGE} . 
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}
    - docker tag ${CONTAINER_IMAGE} ${NAME}
    - docker tag ${CONTAINER_IMAGE} ${LATEST}
    - docker push ${LATEST}
  #     - curl --max-time 900 --silent --fail -H "web-hook-token:$DEV" dev.robolucha.com:4295/dev-docs
  only:
    - development
