image: docker:19.03.11
services:
  - docker:19.03.11-dind

variables:
  NAME: robolucha/game
  BUILD: ${NAME}:${CI_COMMIT_SHORT_SHA}
  LATEST: ${NAME}:latest
  PUSH_BUILD: ${DOCKER_SERVER}/${BUILD}
  PUSH_LATEST: ${DOCKER_SERVER}/${LATEST}
  
before_script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_SERVER

build:
  stage: build
  script:
    - echo Building $BUILD
    - docker build --cache-from $PUSH_LATEST -t $BUILD . 
    - docker tag $BUILD $PUSH_BUILD
    - docker tag $BUILD $PUSH_LATEST
    - echo Pushing $PUSH_BUILD $PUSH_LATEST 
    - docker push $PUSH_BUILD
    - docker push $PUSH_LATEST
  # - curl --max-time 900 --silent --fail -H "web-hook-token:$DEV" dev.robolucha.com:4295/dev-docs
  only:
    - development
