language: minimal

branches:
  only:
    - master

script:
  - curl -H "web-hook-token:$WEBHOOK_TOKEN" robolucha.com:8095/game | jq .
  - curl -H "web-hook-token:$WEBHOOK_TOKEN" robolucha.com:8095/up | jq .
