/**
 * Robolucha API
 * Robolucha API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MainCode } from './mainCode';
import { MainConfig } from './mainConfig';


export interface MainGameComponent {
    codes?: Array<MainCode>;
    configs?: Array<MainConfig>;
    gameDefinition?: number;
    id?: number;
    name?: string;
    userID?: number;
}
