/**
 * Robolucha API
 * Robolucha API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface MainMatchScore {
    createdAt?: string;
    deaths?: number;
    deletedAt?: string;
    id?: number;
    kills?: number;
    luchadorID?: number;
    matchID?: number;
    score?: number;
    updatedAt?: string;
}
