/**
 * Robolucha API
 * Robolucha API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface MainMatch {
    createdAt?: string;
    deletedAt?: string;
    duration?: number;
    id?: number;
    lastTimeAlive?: string;
    timeEnd?: string;
    timeStart?: string;
    updatedAt?: string;
}
