/**
 * Robolucha API
 * Robolucha API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MainCode } from './mainCode';


export interface MainSceneComponent {
    blockMovement?: boolean;
    codes?: Array<MainCode>;
    colider?: boolean;
    gameDefinition?: number;
    height?: number;
    id?: number;
    name?: string;
    respawn?: boolean;
    rotation?: number;
    showInRadar?: boolean;
    width?: number;
    x?: number;
    y?: number;
}
