/**
 * Robolucha API
 * Robolucha API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MainGameComponent } from './mainGameComponent';


export interface MainMatch {
    gameDefinitionID?: number;
    id?: number;
    lastTimeAlive?: string;
    participants?: Array<MainGameComponent>;
    timeEnd?: string;
    timeStart?: string;
}
