/**
 * Robolucha API
 * Robolucha API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModelCode } from './mainCode';
import { ModelConfig } from './mainConfig';


export interface ModelLuchador {
    codes?: Array<ModelCode>;
    configs?: Array<ModelConfig>;
    createdAt?: string;
    deletedAt?: string;
    id?: number;
    name?: string;
    updatedAt?: string;
    userID?: number;
}
