/**
 * Robolucha API
 * Robolucha API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MainLuchador } from './mainLuchador';


export interface MainMatch {
    arenaHeight?: number;
    arenaWidth?: number;
    buletSpeed?: number;
    bulletSize?: number;
    createdAt?: string;
    deletedAt?: string;
    duration?: number;
    fps?: number;
    id?: number;
    lastTimeAlive?: string;
    luchadorSize?: number;
    maxParticipants?: number;
    minParticipants?: number;
    participants?: Array<MainLuchador>;
    timeEnd?: string;
    timeStart?: string;
    updatedAt?: string;
}
