/**
 * Robolucha API
 * Robolucha API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MainCode } from './mainCode';


export interface MainLuchador {
    codes?: Array<MainCode>;
    createdAt?: string;
    deletedAt?: string;
    id?: number;
    name?: string;
    updatedAt?: string;
    userID?: number;
}
