/**
 * Robolucha API
 * Robolucha API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ModelTeam {
    color?: string;
    id?: number;
    maxParticipants?: number;
    minParticipants?: number;
    name?: string;
    teamDefinition?: number;
}
