/**
 * Robolucha API
 * Robolucha API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModelCode } from './modelCode';
import { ModelGameComponent } from './modelGameComponent';
import { ModelNarrativeDefinition } from './modelNarrativeDefinition';
import { ModelSceneComponent } from './modelSceneComponent';
import { ModelTeamDefinition } from './modelTeamDefinition';


export interface ModelGameDefinition {
    arenaHeight?: number;
    arenaWidth?: number;
    buletSpeed?: number;
    bulletSize?: number;
    codes?: Array<ModelCode>;
    description?: string;
    duration?: number;
    energy?: number;
    fireEnergyCost?: number;
    fps?: number;
    gameComponents?: Array<ModelGameComponent>;
    id?: number;
    increaseSpeedEnergyCost?: number;
    increaseSpeedPercentage?: number;
    label?: string;
    life?: number;
    luchadorSize?: number;
    maxFireAmount?: number;
    maxFireCooldown?: number;
    maxFireDamage?: number;
    maxLevel?: number;
    maxParticipants?: number;
    minFireAmount?: number;
    minFireDamage?: number;
    minLevel?: number;
    minParticipants?: number;
    moveSpeed?: number;
    name?: string;
    narrativeDefinitions?: Array<ModelNarrativeDefinition>;
    ownerUserID?: number;
    punchAngle?: number;
    punchCoolDown?: number;
    punchDamage?: number;
    radarAngle?: number;
    radarRadius?: number;
    recycledLuchadorEnergyRestore?: number;
    respawnAngle?: number;
    respawnCooldown?: number;
    respawnGunAngle?: number;
    respawnX?: number;
    respawnY?: number;
    restoreEnergyperSecond?: number;
    sceneComponents?: Array<ModelSceneComponent>;
    sortOrder?: number;
    suggestedCodes?: Array<ModelCode>;
    teamDefinition?: ModelTeamDefinition;
    turnGunSpeed?: number;
    turnSpeed?: number;
    type?: string;
    unblockLevel?: number;
}
