/**
 * Robolucha API
 * Robolucha API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModelStudent } from './modelStudent';


export interface ModelClassroom {
    accessCode?: string;
    id?: number;
    name?: string;
    ownerID?: number;
    students?: Array<ModelStudent>;
}
