/**
 * Robolucha API
 * Robolucha API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ModelUserSetting {
    id?: number;
    playedTutorial?: boolean;
    userID?: number;
    visitedMainPage?: boolean;
    visitedMaskPage?: boolean;
}
