/**
 * Robolucha API
 * Robolucha API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ModelMedia {
    fileName?: string;
    gameDefinition?: number;
    id?: number;
    narrativeDefinition?: number;
    thumbnail?: string;
    url?: string;
    userID?: number;
}
