/**
 * Robolucha API
 * Robolucha API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ModelPageEventRequest {
    action?: string;
    appName?: string;
    appVersion?: string;
    componentID?: string;
    page?: string;
    value1?: string;
    value2?: string;
    value3?: string;
}
