/**
 * Robolucha API
 * Robolucha API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModelCode } from './modelCode';
import { ModelConfig } from './modelConfig';


export interface ModelGameComponent {
    codes?: Array<ModelCode>;
    configs?: Array<ModelConfig>;
    gameDefinition?: number;
    id?: number;
    name?: string;
    userID?: number;
}
